food <- read.csv("protein.csv")
View(food)
set.seed(1)
grpmeat <- kmeans(food [,c("WhiteMeat","RedMeat")],centers=3,nstart=10)
o <- order(grpmeat$cluster)
data.frame(food$Country[o],grpmeat$cluster)
plot(food$RedMeat,food$WhiteMeat,type="n",xlim=c(3,19),xlab="red meat",ylab="white meat")
text(x=food$RedMeat,y=food$WhiteMeat,labels=food$Country,col=grpmeat$cluster+1)
text(x=food$RedMeat,y=food$WhiteMeat,labels=food$Country,col=grpmeat$cluster+2)
text(x=food$RedMeat,y=food$WhiteMeat,labels=food$Country,col=grpmeat$cluster+3)